#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hackatown_2018.Resource", IsApplication=true)]

namespace Hackatown_2018
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int hour_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_notif = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int addAlarm = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int alarmTime = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int arrivalTime = 2131099650;
			
			// aapt resource value: 0x7f06001c
			public const int btnConfirmerNew = 2131099676;
			
			// aapt resource value: 0x7f060012
			public const int btnDate = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int btnDateConfirm = 2131099660;
			
			// aapt resource value: 0x7f06001b
			public const int btnDest = 2131099675;
			
			// aapt resource value: 0x7f060004
			public const int btnEdit = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int btnErase = 2131099651;
			
			// aapt resource value: 0x7f060019
			public const int btnPosActuelle = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int btnTime = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int btnTimeConfirm = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int button1 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int button2 = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public const int buttontest = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int datePicker1 = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int dayOfWeek = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int listText = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int map = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int spHour = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int spMinute = 2131099671;
			
			// aapt resource value: 0x7f060005
			public const int text1 = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int textName = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int textView1 = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int textView2 = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int textView3 = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int textView4 = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int textView5 = 2131099674;
			
			// aapt resource value: 0x7f060009
			public const int timePicker1 = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlarmLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Edit = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LayoutMap = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LayoutPickerTime = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LayoutPicketDate = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListViewPerso = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NewItemLayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int hour_prompt = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
